#!/bin/bash
set -em
mkdir -p /tmp/demodb
mongod --quiet --nojournal --smallfiles --port 3014 --dbpath /tmp/demodb >/tmp/demodb.log &
mongod=$!

function killKids {
    kill $mongod 2>/dev/null
}
trap "killKids" SIGCHLD
trap "killKids" 0

mongo localhost:3014/demo
