#!/bin/bash
set -em
mkdir -p /tmp/testdb
mongod --quiet --nojournal --smallfiles --port 3004 --dbpath /tmp/testdb >/tmp/testdb.log &
mongod=$!

function killKids {
    kill $mongod 2>/dev/null
}
trap "killKids" SIGCHLD
trap "killKids" 0

mongo localhost:3004/test
