#!/bin/bash
set -e

branch="${1-demo}"

if [ "$MONGO_DIR" = "" ];then
    . `dirname "$0"`/environ.sh
fi

# export NODE_OPTIONS='--prof'
# send SIGUSR1 to debug

# export UV_THREADPOOL_SIZE=8


if [ "`which mongod`" != "" ];then
    export KORU_USE_MONGO=1
    fuser -s "$MONGO_DIR/mongod.lock" || ./scripts/startdb.sh $branch
else
    unset KORU_USE_MONGO
fi
cd app
echo -e "starting ${branch}...\c"
exec ${NODEDEBUG-node} --es_staging --expose-gc ../lib/koru.js "$@"
